---
name: build
on: [deployment, push]

jobs:
  github-container-registory:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [almalinux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container resigtory
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT}}

      - name: Build and push
        uses: ocker/build-push-action@v1
        with:
          dockerfile: ${{ matrix.images }}/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: docker.pkg.github.com
          repository: ttanaka9211/${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_VERSION }}
